### ISSUE TITLE
Error Running predict on cityscapes with python 2.7

### ISSUE THREAD

**Issue by uyekt** [TobyPDE/FRRN#26]
Hi there,

I wanted to test your network, but somehow I can't get ride of this error:

>   File "/media/---/Volume/---/FRRN/dltools/data.py", line 245, in <lambda>
    self._map_func = np.vectorize(lambda px: self._intensity_map[px])
TypeError: list indices must be integers, not NoneType

Do I miss something, or is there a problem with the code?
I use Anaconda environment with python 2.7 on Ubuntu 16.04 with Cuda 8.
The dependencies are installed:

> python check_dependencies.py --cs_folder=cityscapes_lk
2017-08-05 10:23:13,954 INFO Found supported Python version 2.7.
2017-08-05 10:23:13,979 INFO Successfully imported numpy.
2017-08-05 10:23:13,998 INFO Successfully imported cv2.
2017-08-05 10:23:14,096 INFO Successfully imported sklearn.
2017-08-05 10:23:14,098 INFO Successfully imported sklearn.metrics.
2017-08-05 10:23:14,098 INFO Successfully imported scipy.
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29
2017-08-05 10:23:14,223 WARNING The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29
Using gpu device 1: GeForce GTX 1080 (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 5110)
2017-08-05 10:23:15,236 INFO Successfully imported theano.
2017-08-05 10:23:15,239 INFO Successfully imported lasagne.
2017-08-05 10:23:15,239 INFO Theano float is float32.
2017-08-05 10:23:15,240 INFO cuDNN spatial softmax found.
2017-08-05 10:23:15,241 INFO Chianti C++ library is not available. Will default to slower Python implementation.
2017-08-05 10:23:15,249 INFO Found CityScapes training set.
2017-08-05 10:23:15,250 INFO Found CityScapes validation set.

Full Traceback until ctrl-c:

> python predict.py --architecture frrn_a --model_file models/frrn_a.npz --cs_folder cityscapes_lk 
WARNING (theano.sandbox.cuda): The cuda backend is deprecated and will be removed in the next release (v0.10).  Please switch to the gpuarray backend. You can get more information about how to switch at this URL:
 https://github.com/Theano/Theano/wiki/Converting-to-the-new-gpu-back-end%28gpuarray%29
Using gpu device 1: GeForce GTX 1080 (CNMeM is enabled with initial size: 95.0% of memory, cuDNN 5110)
2017-08-05 10:23:23,614 INFO Compile validation function
Process Process-2:
Traceback (most recent call last):
  File "/home/---/anaconda3/envs/frnn/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/---/anaconda3/envs/frnn/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/media/---/Volume/---/FRRN/dltools/data.py", line 70, in __init__
    self.start_loading()
  File "/media/---/Volume/---/FRRN/dltools/data.py", line 78, in start_loading
    images, targets = self.load_batch()
  File "/media/---/Volume/---/FRRN/dltools/data.py", line 87, in load_batch
    data = [self._data_loader.get_pair() for _ in range(self._batch_size)]
  File "/media/---/Volume/---/FRRN/dltools/data.py", line 47, in get_pair
    target = self._target_loader.load(target_file)
  File "/media/---/Volume/---/FRRN/dltools/data.py", line 257, in load
    img = self._map_func(img)
  File "/home/---/anaconda3/envs/frnn/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2734, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/---/anaconda3/envs/frnn/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2804, in _vectorize_call
    ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
  File "/home/---/anaconda3/envs/frnn/lib/python2.7/site-packages/numpy/lib/function_base.py", line 2764, in _get_ufunc_and_otypes
    outputs = func(*inputs)
  File "/media/---/Volume/---/FRRN/dltools/data.py", line 245, in <lambda>
    self._map_func = np.vectorize(lambda px: self._intensity_map[px])
TypeError: list indices must be integers, not NoneType

Thanks in advance!

**Comment by TobyPDE** [comment]
Hey, 
Thanks for reporting this. I'm pretty sure that this is a bug. I will have a closer look on the weekend.

**Comment by zhang412yi** [comment]
cp -r local/lib/libchianti.so /usr/local/cuda/lib64/
![image](https://user-images.githubusercontent.com/27990874/33054019-bc91e2c4-ceb1-11e7-9d96-595eca6b007f.png)
