### ISSUE TITLE
Chianti TypeError in train.py l264

### ISSUE THREAD

**Issue by uyekt** [TobyPDE/FRRN#29]
Hi there,
I'm really interested in using your network and performance does matter, that's why I installed chianti.
However I get this error:

>python predict.py --architecture frrn_a --model_file models/frrn_a.npz --cs_folder ../Datasets/cityscapes_lk
Using cuDNN version 6021 on context None
Mapped name None to device cuda0: GeForce GTX 960 (0000:01:00.0)
2017-08-11 11:30:03,314 INFO Compile validation function
Traceback (most recent call last):
  File "predict.py", line 84, in <module>
    main()
  File "predict.py", line 63, in main
    BATCH_SIZE)
  File "/---/FRRN/train.py", line 264, in get_validation_provider
    pychianti.Iterator.Sequential(validation_images),
TypeError: No registered converter was able to produce a C++ rvalue of type std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > from this Python object of type str

I'm using python 2.7 in Anaconda. I have all dependencies.  Boost version is 1.64.  I tried different version of boost / boost-python and still got the same error.  Any clue?

**Comment by TobyPDE** [comment]
Hm, this a weird error. It says that it cannot produce a C++ string from a Python string, which is something it should be able to do. I'll have a closer look on Sunday. Thanks for reporting this.

**Comment by uyekt** [comment]
@TobyPDE did you had time to took a look, where it could come from?
