### ISSUE TITLE
how to install theano 0.9.0.dev1?

### ISSUE THREAD

**Issue by gaopeng-eugene** [TobyPDE/FRRN#7]
pip3.5 install theano==0.9.0     

Collecting theano==0.9.0
  Could not find a version that satisfies the requirement theano==0.9.0 (from versions: 0.3.0rc4, 0.3.0, 0.3.1rc1, 0.3.1rc2, 0.3.1, 0.4.0rc1, 0.4.0rc2, 0.4.0rc3, 0.4.0rc4, 0.4.0, 0.4.1rc1, 0.4.1rc2, 0.4.1, 0.5.0rc1, 0.5.0rc2, 0.5.0, 0.6.0rc1, 0.6.0rc2, 0.6.0rc3, 0.6.0rc5, 0.6.0, 0.7.0rc1, 0.7.0rc2, 0.7.0, 0.8.0rc1, 0.8.0, 0.8.1, 0.8.2)

No matching distribution found for theano==0.9.0

**Comment by gaopeng-eugene** [comment]
Can you tell me how to install theano 0.9.0? The default theano for python 3,5 is 0.8.0 by which your code will run into the following error.

**Comment by gaopeng-eugene** [comment]
Enter path to CityScapes folder [/opt/data/penggao/dataset/cityscape]: 
Enter model filename [models/frrn_b.npz]: 
Enter log filename [logs/frrn_b.log]: 
Define network... [0.52s]
Load model... [0.83s]
Define loss... [0.51s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/type.py", line 267, in dtype_specs
    }[self.dtype]
KeyError: 'object'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/basic.py", line 408, in constant_or_value
    TensorType(dtype=x_.dtype, broadcastable=bcastable),
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/type.py", line 50, in __init__
    self.dtype_specs()  # error checking is done there
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/type.py", line 270, in dtype_specs
    % (self.__class__.__name__, self.dtype))
TypeError: Unsupported dtype for TensorType: object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/basic.py", line 202, in as_tensor_variable
    return constant(x, name=name, ndim=ndim)
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/basic.py", line 422, in constant
    dtype=dtype)
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/basic.py", line 417, in constant_or_value
    raise TypeError("Could not convert %s to TensorType" % x, type(x))
TypeError: not all arguments converted during string formatting

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 78, in <module>
    all_predictions, split_outputs = dltools.hybrid_training.get_split_outputs(network, deterministic=False)
  File "/opt/data/penggao/deep_segmentation/FRRN/dltools/hybrid_training.py", line 18, in get_split_outputs
    all_outputs = lasagne.layers.get_output(network.output_layers + sum(network.splits, []), **kwargs)
  File "/usr/local/lib/python3.5/site-packages/lasagne/layers/helper.py", line 191, in get_output
    all_outputs[layer] = layer.get_output_for(layer_inputs, **kwargs)
  File "/opt/data/penggao/deep_segmentation/FRRN/dltools/layers.py", line 36, in get_output_for
    return T.nnet.abstract_conv.bilinear_upsampling(input, self.factor)
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/nnet/abstract_conv.py", line 569, in bilinear_upsampling
    row * ratio, col * ratio))
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/var.py", line 327, in reshape
    return theano.tensor.basic.reshape(self, shape, ndim=ndim)
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/basic.py", line 4526, in reshape
    newshape = as_tensor_variable(newshape)
  File "/usr/local/lib/python3.5/site-packages/theano/tensor/basic.py", line 208, in as_tensor_variable
    raise AsTensorError("Cannot convert %s to TensorType" % str_x, type(x))
theano.tensor.var.AsTensorError: ('Cannot convert (None, None, Elemwise{mul,no_inplace}.0, Elemwise{mul,no_inplace}.0) to TensorType', <class 'tuple'>)

**Comment by TobyPDE** [comment]
Install it via `pip install git+https://github.com/Theano/Theano`.
